# Base de datos embebida
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.platform=h2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate auto-create para test
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT simulado (ya lo mockeas en los tests)
jwt.secret=ClaveJWTparaTestDe32CaracteresSegura
jwt.expiration-ms=86400000
