spring.datasource.url=jdbc:mysql://localhost:3307/incidenciasdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=incidencias_user
spring.datasource.password=incidencias_password
jwt.secret=ultrasecretodevelopment
jwt.expiration-ms=86400000
